name: pipeline_session15

on:
  push:
    branches:
      - main

jobs :
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: clone repo
        uses: actions/checkout@v6

      - name: list branch
        run: git branch

      - run: mkdir folder1
      - name: list folders
        run: ls -al
  
  job2:
    runs-on: ubuntu-latest
    needs : job1
    steps:
      - name: list folders
        run: ls -al

  job3:
    runs-on: ubuntu-latest
    needs : job1
    steps:
      - name: list folders
        run: ls -al

  job4:
    runs-on: ubuntu-latest
    needs : job2
    steps:
      - name: list folders
        run: ls -al

  job5:
    runs-on: ubuntu-latest
    needs : job3
    steps:
      - name: list folders
        run: ls -al